### ISSUE TITLE
Webserver nicht immer erreichbar

### ISSUE THREAD

**Issue by plenet** [data-network-alfeld/ScrollDisplay#1]
webserver schaltet sich aus, wenn interner wlan-ap ausgeht?

**Comment by Manawyrm** [comment]
Oh, ja. 
Das macht die https://github.com/data-network-alfeld/ScrollDisplay/blob/master/src/WLAN.cpp#L36 ... 
Macht wahrscheinlich eher wenig Sinn, oder? 
Ich würde in Zukunft die eigene SSID nach 5 Minuten ohne Clients deaktivieren, das WebGUI aber immer anlassen?

**Comment by plenet** [comment]
Ja das wifiportal sollte den timeout behalten, aber das WebGUI soll natürlich online bleiben, solange das Teil noch in nem Wlan eingebucht ist.

**Comment by Manawyrm** [comment]
Jo, das Verhalten ist jetzt deutlich sinnvoller, WLAN-AP geht immer noch nach ner Weile aus (nur wenn keine Clients drauf sind), aber das WebIf im eigenen WLAN ist permanent aktiv.
