### ISSUE TITLE
Verschiedene Modi auswählbar

### ISSUE THREAD

**Issue by Manawyrm** [data-network-alfeld/ScrollDisplay#4]
Zwischen Scrolltext, Uhrzeit und Temperatur müsste irgendwie entweder hin- und hergewechselt werden können, oder automatisch dazwischen umgeschaltet werden. 

Ideen?

**Comment by plenet** [comment]
könnte mir vorstellen, dass man in der GUI ankreuzt welche werte angezeigt werden sollen, und die dann mittels der animation und delay durchlaufen.
Oder sogar nen eigenen delay für jeden Wert

**Comment by ernie76** [comment]
habe es im menü erstmal per select eingebaut.
man kann dort zwischen scrolltext, uhrzeit, und uhrzeit mit datum wählen.
