### ISSUE TITLE
Config für Displaygröße und hostname

### ISSUE THREAD

**Issue by plenet** [data-network-alfeld/ScrollDisplay#5]

**Comment by Manawyrm** [comment]
Jo, gute Idee. 
Über die Configuration.h, über das WebGUI oder über das Menü? 

Ich nehme an, das würde gut ins WebGUI passen?

**Comment by plenet** [comment]
hatte eigentlich nur an die config.h gedacht. aber WebGUI wär natürlich auch nett

**Comment by Manawyrm** [comment]
Man könnte den Hostnamen dann auch gleichzeitig als SSID für den AP nehmen. 2 Fliegen mit einer Klappe...

**Comment by Manawyrm** [comment]
741f4df4c507e1ab30b33b784f36c77ed9a13e9d implementiert das. 

WebGUI für Hostnamen merk ich mir.
